//
//  PlacesClass.swift
//  sukunat
//
//  Created by Xan Xanzaki on 23/11/25.
//

import UIKit
class PlacesClass{
    static let placesArray: [PlacesModel] = [
        PlacesModel(placesImage: UIImage(named: "AlisherNavoiLibrary"),placesNames: "National Library of Uzbekistan", placesLocationName: "Tashkent", category: "Popular", type: "Libraries"),
        PlacesModel(placesImage: UIImage(named: "StateInstitudeLibrary"),placesNames: "Tashkent State Institute Library", placesLocationName: "Tashkent", category: "Recommendations", type: "Libraries"),
        PlacesModel(placesImage: UIImage(named: "SamarkandLibrary"),placesNames: "Samarkand Regional Library", placesLocationName: "Samarkand", category: "All", type: "Libraries"),
        PlacesModel(placesImage: UIImage(named: "BukharaRegionalLibrary"),placesNames: "Bukhara Regional Scientific Library", placesLocationName: "Bukhara", category: "Recommendations", type: "Libraries"),
        PlacesModel(placesImage: UIImage(named: "FerghanaLibrary"),placesNames: "Fergana Regional Library", placesLocationName: "Ferghana", category: "All", type: "Libraries"),
        PlacesModel(placesImage: UIImage(named: "NamanganRegionalLibrary"),placesNames: "Namangan Regional Library", placesLocationName: "Namangan", category: "All", type: "Libraries"),
        PlacesModel(placesImage: UIImage(named: "NukusLibrary"),placesNames: "Nukus Karakalpakstan Library", placesLocationName: "Nukus", category: "All", type: "Libraries"),
        PlacesModel(placesImage: UIImage(named: "TashkentBotanicalGarden"),placesNames: "Tashkent Botanical Garden", placesLocationName: "Tashkent", category: "All", type: "Botanical Gardens"),
        PlacesModel(placesImage: UIImage(named: "FerghanaBotanicalGarden"),placesNames: "Fergana Botanical Park", placesLocationName: "Ferghana", category: "All", type: "Botanical Gardens"),
        PlacesModel(placesImage: UIImage(named: "AndijanGreenPark"),placesNames: "Andijan Green Park", placesLocationName: "Andijan", category: "Popular", type: "Botanical Gardens"),
        PlacesModel(placesImage: UIImage(named: "NukusBotanicalGarden"),placesNames: "Nukus Botanical Area", placesLocationName: "Nukus", category: "All", type: "Botanical Gardens"),
        PlacesModel(placesImage: UIImage(named: "UrgenchBotanicalGarden"),placesNames: "Urgench Botanical Green Area", placesLocationName: "Urgench", category: "All", type: "Botanical Gardens"),
        PlacesModel(placesImage: UIImage(named: "BukharaGreenPark"),placesNames: "Bukhara Green Garden", placesLocationName: "Bukhara", category: "Recommendations", type: "Botanical Gardens"),
        PlacesModel(placesImage: UIImage(named: "StateMuseumTashkent"),placesNames: "State Museum of History of Uzbekistan", placesLocationName: "Tashkent", category: "Popular", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "SavitskyNukus"),placesNames: "Savitsky Art Museum", placesLocationName: "Nukus", category: "Recommendations", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "AfrasiyabSamarkan"),placesNames: "Afrasiab Museum", placesLocationName: "Samarkand", category: "All", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "Gur-e-AmirSamarkand"),placesNames: "Gur-e-Amir Museum", placesLocationName: "Samarkand", category: "Popular", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "BukharaArkMuseum"),placesNames: "Bukhara Ark Museum", placesLocationName: "Bukhara", category: "Popular", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "AndijanMuseum"),placesNames: "Andijan Regional Museum", placesLocationName: "Andijan", category: "All", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "KhivaIchanKala"),placesNames: "Khiva Ichan Kala Museum Complex", placesLocationName: "Khiva", category: "Popular", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "FerghanaMuseum"),placesNames: "Fergana Regional Museum", placesLocationName: "Ferghana", category: "Popular", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "TermezMuseum"),placesNames: "Termez Archaeology Museum", placesLocationName: "Termez", category: "Popular", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "RailwayTashkent"),placesNames: "Tashkent Railway Museum", placesLocationName: "Tashkent", category: "All", type: "Museums"),
        PlacesModel(placesImage: UIImage(named: "KitobOlamiTashkent"),placesNames: "Kitob Olami (Tashkent)", placesLocationName: "Tashkent", category: "All", type: "Bookstores"),
        PlacesModel(placesImage: UIImage(named: "MirKnigTashkent"),placesNames: "Mir Knig Bookstore (Tashkent)", placesLocationName: "Tashkent", category: "All", type: "Bookstores"),
        PlacesModel(placesImage: UIImage(named: "FerghanaBookStore"),placesNames: "Ferghana Book Store", placesLocationName: "Ferghana", category: "All", type: "Bookstores"),
        PlacesModel(placesImage: UIImage(named: "SamarkandBookMarket"),placesNames: "Samarkand Book Store", placesLocationName: "Samarkand", category: "All", type: "Bookstores"),
        PlacesModel(placesImage: UIImage(named: "NamanganBookStore"),placesNames: "Namangan Book Store", placesLocationName: "Namangan", category: "All", type: "Bookstores"),
        PlacesModel(placesImage: UIImage(named: "MinorMosqueTashkent"),placesNames: "Minor Mosque", placesLocationName: "Tashkent", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "HazratiImamTashkent"),placesNames: "Hazrati Imam Complex", placesLocationName: "Tashkent", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "KukaldeshTashkent"),placesNames: "Kukeldash Mosque", placesLocationName: "Tashkent", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "BibiKhanimSamarkand"),placesNames: "Bibi-Khanym Mosque", placesLocationName: "Samarkand", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "KalonMosque"),placesNames: "Kalon Mosque", placesLocationName: "Bukhara", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "MagokiAttoriMosque"),placesNames: "Magoki-Attori Mosque", placesLocationName: "Bukhara", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "JumaMosqueKhiva"),placesNames: "Juma Mosque", placesLocationName: "Khiva", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "JamiMosqueAndijan"),placesNames: "Andijan Jami Mosque", placesLocationName: "Andijan", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "FerghanaMosque"),placesNames: "Fergana Jome Mosque", placesLocationName: "Andijan", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "NamanganMosque"),placesNames: "Namangan Central Mosque", placesLocationName: "Namangan", category: "Popular", type: "Mosques"),
        PlacesModel(placesImage: UIImage(named: "TashkentCityPark"),placesNames: "Tashkent City Park", placesLocationName: "Tashkent", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "CentralParkTashkent"),placesNames: "Central Park", placesLocationName: "Tashkent", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "AshkabadParkTashkent"),placesNames: "Ashgabat Park", placesLocationName: "Tashkent", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "AmirTemurParkTashkent"),placesNames: "Amir Temur Park", placesLocationName: "Tashkent", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "NavoiParkSamarkand"),placesNames: "Navoi Park (Samarkand)", placesLocationName: "Samarkand", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "SitoraiMohiHosaBukhara"),placesNames: "Sitorai Mokhi-Khosa Garden", placesLocationName: "Bukhara", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "OldTownKhiva"),placesNames: "Khiva Old Town Green Zone", placesLocationName: "Khiva", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "FerghaniyParkFerghana"),placesNames: "Fergana Al-Fergani Park", placesLocationName: "Ferghana", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "BoburParkAndijan"),placesNames: "Andijan Bog’i Bobur", placesLocationName: "Andijan", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "NukusCentralPark"),placesNames: "Nukus Central Park", placesLocationName: "Nukus", category: "Recommendations", type: "Parks"),
        PlacesModel(placesImage: UIImage(named: "BookCafeTashkent"),placesNames: "BookCafe", placesLocationName: "Tashkent", category: "All", type: "Cafés"),
        PlacesModel(placesImage: UIImage(named: "BreadlyCafe"),placesNames: "Breadly Café", placesLocationName: "Tashkent", category: "All", type: "Cafés"),
        PlacesModel(placesImage: UIImage(named: "BlackBearCafeTashkent"),placesNames: "Black Bear Café", placesLocationName: "Tashkent", category: "All", type: "Cafés"),
        PlacesModel(placesImage: UIImage(named: "ManzaraCafeSamarkand"),placesNames: "Samarkand Manzara Café", placesLocationName: "Samarkand", category: "All", type: "Cafés"),
        PlacesModel(placesImage: UIImage(named: "SilkRoadCafe"),placesNames: "Bukhara Silk Road Coffee", placesLocationName: "Bukhara", category: "All", type: "Cafés"),
        PlacesModel(placesImage: UIImage(named: "ChimganMountains"),placesNames: "Chimgan Mountains", placesLocationName: "Tashkent", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "Beldersay"),placesNames: "Beldersay", placesLocationName: "Tashkent", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "Amirsoy"),placesNames: "Amirsoy Resort", placesLocationName: "Tashkent", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "Nanai"),placesNames: "Nanai Mountains", placesLocationName: "Tashkent", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "PskemValley"),placesNames: "Pskem Valley", placesLocationName: "Tashkent", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "UgamRange"),placesNames: "Ugam Range", placesLocationName: "Tashkent", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "ZaminNationalPark"),placesNames: "Zaamin National Park (mountain area)", placesLocationName: "Jizzakh", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "KitabMountains"),placesNames: "Kitab Reserve Mountains", placesLocationName: "Kashkadarya", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "BaysunMountains"),placesNames: "Boysun Mountains", placesLocationName: "Surkhandarya", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "HisorMountains"),placesNames: "Hisor Mountain Range", placesLocationName: "Uzbekisdan and Tadjikistan", category: "All", type: "Mountains"),
        PlacesModel(placesImage: UIImage(named: "CSpaceCoworking"),placesNames: "CSpace Coworking", placesLocationName: "Tashkent", category: "All", type: "Coworking Centers"),
        PlacesModel(placesImage: UIImage(named: "GroundZeroCoworking"),placesNames: "Ground Zero", placesLocationName: "Tashkent", category: "All", type: "Coworking Centers"),
        PlacesModel(placesImage: UIImage(named: "ImpactHubTashkent"),placesNames: "Impact Hub", placesLocationName: "Tashkent", category: "All", type: "Coworking Centers"),
        PlacesModel(placesImage: UIImage(named: "LOFT"),placesNames: "LOFT Coworking", placesLocationName: "Tashkent", category: "All", type: "Coworking Centers"),
        PlacesModel(placesImage: UIImage(named: "KonigilVillageSamarkand"),placesNames: "Konigil Village", placesLocationName: "Samarkand", category: "Recommendations", type: "Small Villages"),
        PlacesModel(placesImage: UIImage(named: "SentobNavoi"),placesNames: "Sentob Village", placesLocationName: "Navoi", category: "Popular", type: "Small Villages"),
        PlacesModel(placesImage: UIImage(named: "AsrafNurata"),placesNames: "Asraf Village", placesLocationName: "Navoi", category: "Popular", type: "Small Villages"),
        PlacesModel(placesImage: UIImage(named: "UhumVillage"),placesNames: "Uhum Village", placesLocationName: "Samarkand", category: "Popular", type: "Small Villages"),
        PlacesModel(placesImage: UIImage(named: "VarakshaVillageBukhara"),placesNames: "Varakhsha Village", placesLocationName: "Bukhara", category: "Popular", type: "Small Villages"),
        PlacesModel(placesImage: UIImage(named: "KurgantepaAndijan"),placesNames: "Qo‘rg‘ontepa Village", placesLocationName: "Andijan", category: "Popular", type: "Small Villages"),
        PlacesModel(placesImage: UIImage(named: "NanayCharvak"),placesNames: "Nanay Village", placesLocationName: "Tashkent", category: "All", type: "Small Villages"),
    ]
}
class CategoryClass{
    static var categoryArray: [CategoryModel] = [
        CategoryModel(categoryImage: UIImage(named: "villages")!, categoryName: "Villages", type: "villages"),
        CategoryModel(categoryImage: UIImage(named: "mountains")!, categoryName: "Mountains", type: "mountains"),
        CategoryModel(categoryImage: UIImage(named: "parks")!, categoryName: "Parks", type: "parks"),
        CategoryModel(categoryImage: UIImage(named: "museums")!, categoryName: "Museums", type: "museums"),
        CategoryModel(categoryImage: UIImage(named: "libraries")!, categoryName: "Libraries", type: "libraries"),
        CategoryModel(categoryImage: UIImage(named: "mosques")!, categoryName: "Mosques", type: "mosques"),
        CategoryModel(categoryImage: UIImage(named: "bookstore")!, categoryName: "Bookstore", type: "bookstore"),
    ]
}
